travis:
  secure:
    BINSTAR_TOKEN: PDgEMB4Zxw0hDjzaCI0mdWgqr8Fr0nlBmR+jW8WIgj3hg9EQDl4VLV4BhxgHZT9yhNBEI7XfqM8o8/w+hQ6e9HK4P2Fh7JVJkupkTRIieXjl0L6EXOciX9HOkbOqw8JxyzSmi4LS+ALJoJ22+iiLaD7gNIBbD+ldB5pZ+6d52ews8m22RoPhIQ7KgICEKtkcTt3OdUtx9G//A/T8VoKvsqwBC7hKnz7k+dUprzlvhUMa96gNPgdlvVlqy+2BR4noycTlM7yxd5fYXdCJ1wGWMsk37ZYEyZadlXZLyB2E1LZfSUwcAb5zMoXpYZv95SL+RifXfjNb9sNpMCPgw6asAcxrm/mYVRky1pVfYhO3QBMwiCPHExPEd/mSYVZpGx0HkJmDUWGing+TVgU2xAcuV50j55uRHoIQhCexLBe3LQYA+pNiiLE3oR/lYHpAetAq+DEpxd8MaQ9sOvX8v0bQpCeNW4Mx5paqLyYIOR4li4MhUvrhBmu5Du0zT21ttEocbYWwANRHkkyTDXD3g5+YqYOK4OnuYq/rUDtXubwKF91+kalVrmEdUiaxXmrgNFw6ShjDcQ25BZTJX59oPpQnXr07bxdDp/hMhOJQUhOxHZOVS/mN9xBclV01GNoJAfFfI9EqgEjL2os65cpz7+hEpO0IgPR7I1VOCpF0cxwiYc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
