travis:
  secure:
    BINSTAR_TOKEN: KkiE4fzJlaTk80QCsPdOK1iGxyLyRJQa1iL/GvAPUT5SMZd30VXCCjtFHCKb0GHVqX293AYK+SKmoAlJY62U2mqg648jbG8Fns3NjSyts8poExOOu3II67vUUPV4WdgeWP0iuOzsPL2xO+ANxj6xCpN6JW7J0u1M2QDK9L3tkr98APaP7nhNNpjWT8QceOeanKGSJn5rE33N84Q9vwEQTPGPR9c4H6YOPE8E1rG8XOSghyOk1dw9fwCy/Wka0SXUAAMJglvXOL4WIyuaOQGUc5nJVHp/aAYsiIWT/gZgG51B21UnAZYDGIUc6/r7G8L46ZPhhZbiKNrrFLPBLTAKh9CtGSk4Eqt0IMAqr0H5v8bsbn38ufRUKf2DnD4p00GF8S2yCmu52wsN2NUTPtTDeL/IgNAUKMMihBryxMok/uxdV3h3IUM7tm2BWgukUejPklD2gnmwh1PCO7efo+ba7WIQltWq069lZak6OljsVf/brXlr4yq51aZMQbf9zW80x3RTYaGehIg8e/XO776/0IYSDux0cv78Y4lSGpPKGovGiPc7AhAgw5QzZYUmQHkwhklz4Emb/17YxbSwQtTIc5k96IXAG6OVNNx2Li7Ye6ADPUfG0XOF67smd3GZ1RxHhAC715gFPskbTbmkIjBoHnpXIWn6SLILe19qGijFaE4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
